version: '3.6'
services:
  pluto_rs:
    container_name: pluto
    build: .
    user: "ferris"
    ports:
    - "3030:3030"
    depends_on:
    - "migration"
    environment:
      DATABASE_URL: ${DATABASE_URL}