version: '3.6'
services:
  pluto_rs_test:
    build: 
      context: .
      dockerfile: ./Dockerfile.test
    # ports:
    # - "3030:3030"
    depends_on:
    - "migration"
    command: "cargo test --test integration"
    environment:
      ## postgres database to store Hasura metadata
      DATABASE_URL: ${DATABASE_URL}

