name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: cp .env.example .env
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
      - name: Test
        run: docker run --network container:pluto appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3030/healthz